name: shelf_example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'


dependencies: {
  shelf_router: ^1.1.3,
  objectbox: ^1.6.2,}

dev_dependencies:

  test: ^1.16.0
  build_runner: ^2.0.0
  objectbox_generator: any
  lints: ^2.0.0